global:
  scrape_interval: 15s
  evaluation_interval: 15s

storage:
  exemplars:
    max_exemplars: 100000

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'otel_demo_.*'
        action: keep
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'otel-collector'

  - job_name: 'java-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['java-service:8081']
        labels:
          service: 'java-spring-boot'
