global:
  scrape_interval: 15s
  evaluation_interval: 15s

storage:
  exemplars:
    max_exemplars: 100000

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    metric_relabel_configs:
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'

  - job_name: 'java-actuator'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['java-service:8081']

  - job_name: 'java-otel'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['java-service:9464']
